version: '3.8'

services:
  db:
    image: postgres:17
    container_name: easylims-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data-model.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: easylims-server
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    depends_on:
      - db
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: easylims-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "8081:80"
    depends_on:
      - db
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    restart: unless-stopped

volumes:
  postgres_data:
