-- Tickets Database Schema DDL for Supabase PostgreSQL
-- Run this script in the SQL Editor of your Supabase Console if tables or foreign keys are missing.

-- 1. Tickets Table
CREATE TABLE IF NOT EXISTS public.tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  attachments JSONB DEFAULT '[]'::jsonb,
  department TEXT DEFAULT 'General',
  priority TEXT DEFAULT 'medium',
  status TEXT DEFAULT 'OPEN',
  created_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Ticket Comments Table
CREATE TABLE IF NOT EXISTS public.ticket_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
  author_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  comment TEXT NOT NULL,
  attachments JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Ticket History Table
CREATE TABLE IF NOT EXISTS public.ticket_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  field_name TEXT NOT NULL,
  old_value TEXT,
  new_value TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure Foreign Key Constraints Exist (for PostgREST explicit relationship joins)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_name = 'ticket_comments_author_id_fkey'
  ) THEN
    ALTER TABLE public.ticket_comments 
    ADD CONSTRAINT ticket_comments_author_id_fkey 
    FOREIGN KEY (author_id) REFERENCES public.users(id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_name = 'tickets_created_by_fkey'
  ) THEN
    ALTER TABLE public.tickets 
    ADD CONSTRAINT tickets_created_by_fkey 
    FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_name = 'ticket_history_user_id_fkey'
  ) THEN
    ALTER TABLE public.ticket_history 
    ADD CONSTRAINT ticket_history_user_id_fkey 
    FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;
  END IF;
END $$;
