-- Easy-LIMS Ticketing System Schema Setup
-- Run this script in your Supabase SQL Editor to set up the database tables.

-- Create tickets table
CREATE TABLE IF NOT EXISTS "public"."tickets" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" text NOT NULL,
    "description" text,
    "attachments" jsonb DEFAULT '[]'::jsonb,
    "department" text NOT NULL,
    "priority" text NOT NULL CHECK (priority IN ('low', 'medium', 'high')),
    "status" text NOT NULL DEFAULT 'Open',
    "created_at" timestamp with time zone DEFAULT now(),
    "created_by" bigint REFERENCES "public"."users"("id") ON DELETE SET NULL
);

-- Create ticket_comments table
CREATE TABLE IF NOT EXISTS "public"."ticket_comments" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ticket_id" bigint REFERENCES "public"."tickets"("id") ON DELETE CASCADE,
    "author_id" bigint REFERENCES "public"."users"("id") ON DELETE SET NULL,
    "comment" text NOT NULL,
    "attachments" jsonb DEFAULT '[]'::jsonb,
    "created_at" timestamp with time zone DEFAULT now()
);

-- Enable Row Level Security (RLS)
ALTER TABLE "public"."tickets" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ticket_comments" ENABLE ROW LEVEL SECURITY;

-- Enable public access policies to align with client-side user sessions
CREATE POLICY "Allow public management of tickets" ON "public"."tickets" USING (true) WITH CHECK (true);
CREATE POLICY "Tickets are viewable by everyone" ON "public"."tickets" FOR SELECT USING (true);

CREATE POLICY "Allow public management of ticket_comments" ON "public"."ticket_comments" USING (true) WITH CHECK (true);
CREATE POLICY "Ticket comments are viewable by everyone" ON "public"."ticket_comments" FOR SELECT USING (true);

-- Create a storage bucket for ticket attachments
INSERT INTO storage.buckets (id, name, public)
VALUES ('ticket-attachments', 'ticket-attachments', true)
ON CONFLICT (id) DO NOTHING;

-- Allow public access to read files in the bucket
CREATE POLICY "Allow public read access to ticket-attachments"
ON storage.objects FOR SELECT
USING (bucket_id = 'ticket-attachments');

-- Allow public access to upload files to the bucket
CREATE POLICY "Allow public insert access to ticket-attachments"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'ticket-attachments');
