from fastapi import APIRouter
from . import client_test_prices
from . import clients
from . import tests
from . import app_settings
from . import bank_accounts
from . import client_service_prices
from . import services
from . import audit_logs
from . import users
from . import company_calendar
from . import expenses
from . import inquiries
from . import hsn_sac_codes
from . import job_tests
from . import jobs
from . import job_to_technicians
from . import documents
from . import collection_centers
from . import material_samples
from . import material_inward_register
from . import request_approvals
from . import sampling
from . import sampling_to_technicals
from . import technicals
from . import service_unit_types
from . import reports
from . import sampling_to_terms_conditions
from . import terms_and_conditions
from . import test_to_technicals
from . import service_to_technicals
from . import service_to_terms_conditions
from . import technician_capabilities
from . import test_to_terms_conditions
from . import job_workflow_logs
from . import sampling_to_materials
